services:
  training-postgres:
    container_name: training-postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=employees
      - POSTGRES_USER=employees
      - POSTGRES_PASSWORD=employees
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgress/data:/var/lib/postgresql

  training-mongodb:
    container_name: training-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=employees
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/data:/data/db

  training-redis:
    container_name: training-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
