spring.application.name=spring-boot-reactiv

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/employees
spring.r2dbc.username=employees
spring.r2dbc.password=employees

#spring.mongodb.uri=mongodb://localhost:27017/employees
spring.mongodb.database=employees
spring.mongodb.host=localhost
spring.mongodb.port=27017
#spring.mongodb.username=employees
#spring.mongodb.password=employees

spring.cloud.stream.bindings.employeesEvents.destination=employees-events
spring.cloud.function.definition=employeeEventsHandler
spring.cloud.stream.bindings.employeeEventsHandler-in-0.destination=employees-events